### ISSUE TITLE
microzed with fmc

### ISSUE THREAD

**Issue by imanyakin** [Avnet/bdf#4]
Hi, looking at this repo I'm trying to understand why picozed has a bdf with an fmc carrier while a microzed - which also has an FMC carrier board is not included?

**Comment by narrucmot** [comment]
This is because the MicroZed is self contained (power subsystem, Ethernet, UART, etc.) and can be used without a carrier card, but the PicoZed is not.  The PicoZed requires being mounted to a carrier card, so the definition of the interfaces on the carrier are included in the PicoZed BDF file.

**Comment by imanyakin** [comment]
ok that makes sense thank you, one more thing - are there known compatibility issues with the bdfs of this repo and Vivado 2019.2? If so - are there more recent bdfs for microzed for vivado 2019.2?

**Comment by narrucmot** [comment]
There are no known compatibility issues with the bdf files in the github repo and the 2019.x and 2020.x Vivado tools.

--Tom
