### ISSUE TITLE
Not working with Vivado/Vitis 2020.3

### ISSUE THREAD

**Issue by kamarya** [Avnet/bdf#9]
After copying the board definitions (as explained in the docs) the boards do not show up under the boards in Vivado 2020.3

It worked with Vivado 2020.2

**Comment by zedman2000** [comment]
Hi there, 
Please move this discussion over to Element14 forums.  We provide all support over there.
https://www.element14.com/community/community/designcenterzedboardcommunity/zedboard-forums
Please gather up what docs you are referring to and I can see about answering you there.
